classical_algorithms/radix.py

radix sort in python

---

classical_algorithms/MergeSort.java

Merge Sort in Java has been performed through Divide and Conquer method.
#12

 Added Merge Sort in Java 

---

classical_algorithms/mergesort.cpp

mergesort.cpp added in classical_algorithms folder #4

mergesort algorithm in c++

---

classical_algorithms/kadanes_algorithm.py

Hi !
I have added **Kadane's Algorithm** in the classical_algorithms section. Kadane's algorithm usually finds its application in many different problems, hence I thought of adding it.
Please review the code and suggest any changes (if any).
Thanks.

Added kadane's algorithm

---

leetcode/java/linkedlist/19.java

Added Leetcode solution in java to problem: Remove nth node from end in a linked list(Q19)

---

classical_algorithms/c++/binary_tree.cpp

Added deletion of node functionality to Binary Tree code in c++

---

classical_algorithms/c++/quicksort.cpp

I've also explained why randomized quick sort is better.

Added Quick Sort and Randomized Quick Sort

---

leetcode/cpp/Tree/662.cpp

Hello! 
I have added solution to leetcode #662. Kindly accept my pull request.
problem link is: https://leetcode.com/problems/maximum-width-of-binary-tree/

Solution for leetcode #662

---

leetcode/cpp/Tree/105.cpp
leetcode/cpp/Tree/106.cpp

Simple clean and time efficient(USES MAP) code for building a Binary Tree given its Preorder and Inorder in problem 105 and Inorder and Postorder Traversal in 106.cpp  from Leetcode.

Added 105.cpp and 106.cpp from Leetcode

---

Project Euler/112.cpp
Project Euler/18.cpp
Project Euler/26.cpp
Project Euler/27.cpp
Project Euler/40.cpp
Project Euler/62.cpp
Project Euler/67.cpp
Project Euler/87.cpp
Project Euler/problem46.cpp
Project Euler/problem79.cpp
Project Euler/problem95.cpp

submitting solutions for issue #54 
All solutions are tested & every solution is working for project euler problems.

adding project euler problem solutions

---

classical_algorithms/c++/mergesort.cpp

Updated mergeSort.cpp

---

Codeforces_Contests/8_Round_675_Div_2/A.cpp
Codeforces_Contests/8_Round_675_Div_2/B.cpp
Codeforces_Contests/8_Round_675_Div_2/C.cpp

Codeforces round 675 (Div 2) solutions of problem A,B and C (in C++)

Added solutions of Div2_Round#675

---

leetcode/cpp/Greedy/minimum_subsequence_in_non_increasing_order.cpp

Contains solution for the problem Minimum Subsequence in Non-Increasing Order (https://leetcode.com/problems/minimum-subsequence-in-non-increasing-order/)

Add cpp code for leetcode problem

---

Hackerrank/Problem Solving/LoneyInteger.cpp

C++ Solution of Lonely Problem of Hackerrank

Lonely Integer Problem of Hackerrank

---

classical_algorithms/c++/Quick Sort.cpp

Hey, @larissalages sorry for the delay, I hope you understand.
I have added the quicksort using c++ under the `classical_algorithms` folder. Please check that out.
Please add `hacktoberfest-accepted` label to my PR before merging. Thank you 😄

added quick sort using c++

---

Patterns/double_sided_arrow_pattern.cpp

hello ,
I would like to add a pattern problem in your repository. Please accept my PR.
Thank You

double_sided_arrow_pattern

---

leetcode/cpp/dynamic programming/174.cpp
readme.md

-LeetCode/Dynamic Programming/174.cpp added
-Dynamic Programming section created in README.md and all the LeetCode solutions available under Dynamic Programming added in the section

LeetCode/DynamicProgramming/DungeonGame.cpp added and README.md updated

---

data_structures/Cpp/BubbleSort.c

I've made a PR by adding the bubble sort program to Cpp data structure folder as per your request. Kindly review it and merge it. Thanks.

Added Bubble sort program

---

leetcode/cpp/Array/287.cpp
leetcode/cpp/Array/442.cpp
leetcode/cpp/Tree/1305.cpp

Added leetcode problems in cpp

Leetcode Problems

---

leetcode/cpp/backtracking/51.cpp
leetcode/cpp/string/567.cpp

Added backtracking recursive code for the N Queens problem no 51 on Leetcode.

add N Queens (51.cpp)

---

Hackerrank/Problem Solving/Anagram.cpp
Hackerrank/Problem Solving/UtopianTree
Hackerrank/Problem Solving/UtopianTree.cpp

Solution for Hackerrank Problem Solving Utopian Tree and Anagram using C++.

UtopianTree

---

CodeChef_problems/dfs_Batman.cpp

dfs_Batman.cpp

---

CodeChef_problems/Zombies_and_Magic.cpp
data_structures/C++/detect_cycle_dfs.cpp

detect_cycle_dfs.cpp

---

Codeforces_Contests/Global Round 10/A.cpp
Codeforces_Contests/Global Round 10/B.cpp
Codeforces_Contests/Global Round 10/C.cpp
Codeforces_Contests/Global Round 10/D.cpp

Added solutions of following problems of codeforces global round 10: A(Omkar and password), B(Omkar and Infinity clock), C(Omkar and waterslide), D(Omkar and bedwars)

added solutions of codeforces global round 10

---

leetcode/cpp/string/438.cpp

add cpp code above problem in file 438.cpp

Find All Anagrams in a String

---

leetcode/cpp/string/402.cpp

add code for above problem in 402.cpp

Remove k digits

---

leetcode/cpp/Array/1.cpp

The solution to question 1 Two Sum problem from LeetCode.

Added solution for Two Sum Problem in LeetCode #27

---

leetcode/cpp/string/165.cpp

add code for above problem in 165.cpp

Compare Version Numbers

---

CodeChef_problems/Chef and Serves.cpp

Solution of problem code CHSERVE on codechef in C++. 
Let me know if changes required.

Added Chef and Serves problem codechef

---

leetcode/cpp/dynamic programming/91.cpp

Added dynamic programming solution for [Decode Ways](https://leetcode.com/problems/decode-ways/) LeetCode#91.

Added solution for Decode Ways Leetcode#91

---

leetcode/cpp/dynamic programming/62.cpp
leetcode/cpp/dynamic programming/91.cpp

Added dynamic programming solution to Leetcode#62 [Unique Paths](https://leetcode.com/problems/unique-paths/) in cpp.

Added solution to Leetcode#62 Unique Paths

---

leetcode/cpp/Stacks/20.cpp

I have solved a new Leetcode problem (Valid Parentheses) about stacks in c++ , could you please merge it?
thanks in advance

Adding new Leetcode Probem

---

classical_algorithms/python/heapsort.py
classical_algorithms/python/tests/test_heap_sort.py

fixed heapSort and implented unitest

---

readme.md

#58 inserting missing links for unitest in python, and editing the file names for the Code where new files existed

inserted missing links for unitest in python

---

leetcode/cpp/Stacks/32.cpp

Added the solution to leetcode#32 [Longest Valid Parentheses](https://leetcode.com/problems/longest-valid-parentheses/) using stacks in C++.

Added solution to LeetCode#32 in C++

---

leetcode/cpp/Tree/129.cpp

Added the solution to leetcode#129 [Sum Root to Leaf Numbers](https://leetcode.com/problems/sum-root-to-leaf-numbers/) Binary Tree problem in C++.

Added C++ solution to LeetCode#129

---

readme.md

Fixes #145 
Fixed the 404 error, solutions open for when clicking on the links.

Fixed 404 errors

---

leetcode/cpp/string/1605.cpp

Added cpp code for problem 1605 from leetcode.

added cpp code for 1605 leetcode

---

data_structures/Cpp/Graph/UsingList.cpp
data_structures/Cpp/Graph/UsingMatrix.cpp

I have added the graph implementation in CPP which was not present before and have also added the codes for BFS and DFS.
This is in relation to issue #152 
Contibuted by [Vaishnavi Shah](https://github.com/vaishnavirshah)

Added graph implementation in CPP along with DFS and BFS codes

---

.gitignore
classical_algorithms/python/tests/test_kadanes_algorithm.py

Add a test for the kadanes algorithm in Python, see #88.

test: kadanes algorithm

---

classical_algorithms/c++/01_knapsack_problem.cpp
classical_algorithms/c++/Kadane_Algorithm.cpp
readme.md

I have added 0/1 Knapsack problem and Kadane's algorithm in c++.

0/1 Knapsack Problem (Dynamic Programming)

---

Hackerrank/c++/Day_15_Linked_List.cpp
Patterns/Num & Star Patterns/pattern1.cpp
Patterns/Num & Star Patterns/pattern2.cpp
Patterns/Num & Star Patterns/pattern3.cpp
Patterns/Num & Star Patterns/pattern4.cpp
Patterns/Num & Star Patterns/pattern5.cpp
Patterns/Num & Star Patterns/pattern6.cpp
Patterns/Num & Star Patterns/pattern7.cpp
Patterns/Num & Star Patterns/pattern8.cpp

Added solutions to different patterns and Hacker Rank Problem Solution

---

classical_algorithms/c++/Topological_sort.cpp
readme.md

Topological Sort (Graphs)

---

leetcode/cpp/dynamic programming/44.cpp

Added solution for leetcode problem 44 wildcard matching in c++
#27

Leetcode solution added for 44(Wild card matching) in cpp

---

data_structures/Cpp/Stack/LinkedStack.cpp

Stack implemented via linked list

LinkedStack.cpp

---

leetcode/cpp/dynamic programming/714.cpp

Added solution for Leetcode problem 714 (Best time to sell and buy with transaction fee) in c++
#27

Leetcode solution added for 714(Best time to sell and buy with transaction fee) in cpp

---

leetcode/python/linked_lists/add_two_numbers_II.py
leetcode/python/queue_reconstruction_by_height.py

I added the problems Add Two Numbers II and Queue Reconstruction by Height from LeetCode in Python 3.

Added Add Two Numbers II and Queue Reconstruction by Height

---

leetcode/cpp/linkedlist/141.cpp

Adding 141.cpp

---

leetcode/cpp/string/151.cpp

Solution of leetcode problem "Reverse Words in a String" is added in cpp. Added code is simple and optimized solution.

Added leetcode problem "Reverse Words in a String" in c++ with optimized solution --151.cpp 

---

Patterns/Interview-Patterns/pattern1.c
Patterns/Interview-Patterns/pattern2.c
Patterns/Interview-Patterns/pattern3.c
Patterns/Interview-Patterns/pattern4.c

Signed-off-by: Gopal <jaingopal09@gmail.com>
I Added Some Famous Coding Patterns Which Recently Asked in Companies

Interviews Pattern

---

leetcode/cpp/string/28.cpp

leetcode #28 "implement strStr()"

---

leetcode/python/Dynamic Programming/Largest_Divisible_Subset.py

Created a folder for Dynamic Programming for Leetcode and added problem no: 368 - Largest Divisible Subset in python language.

Adding Leetcode Problem 368. Largest Divisible Subset.

---

leetcode/cpp/Array/1296.cpp
leetcode/cpp/Array/1366.cpp
leetcode/cpp/Array/1524.cpp
leetcode/cpp/Array/167.cpp
leetcode/cpp/Array/209.cpp
leetcode/cpp/Array/238.cpp
leetcode/cpp/Array/33.cpp
leetcode/cpp/Array/56.cpp
leetcode/cpp/Array/560.cpp
leetcode/cpp/Array/974.cpp
leetcode/cpp/backtracking/77.cpp
leetcode/cpp/backtracking/78.cpp
leetcode/cpp/backtracking/90.cpp
leetcode/cpp/string/791.cpp

Added leetcode cpp solutions in arrays, strings and backtracking

---

leetcode/cpp/Array/154.cpp

I have created a pull request to add a hard problem no. 154 (https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/) and  added it to the leetcode->cpp->array(path). It has been tested and checked. 

Created the solution for 154

---

CodeChef_problems/long_challenge/april_2020_div2/long20apr1.cpp
CodeChef_problems/long_challenge/april_2020_div2/long20apr2.cpp
CodeChef_problems/long_challenge/april_2020_div2/long20apr3.cpp
CodeChef_problems/long_challenge/april_2020_div2/long20apr4.cpp
CodeChef_problems/long_challenge/april_2020_div2/long20apr5.cpp
CodeChef_problems/long_challenge/april_2020_div2/long20apr6.cpp
CodeChef_problems/long_challenge/april_2020_div2/long20apr7.cpp

Added solutions for long challenge contests for april 2020 div 2

april long challenge

---

CodeChef_problems/Squared Subsequences (SQRDSUB).py
CodeChef_problems/Unit GCD (UNITGCD).cpp

Added code for codechef long challenge problems

---

InterviewBit/ADD ONE TO NUMBER.CPP

-- This code is of the "Add one to number" program of InterviewBit of array section using C++ programming language

Create ADD ONE TO NUMBER.CPP

---

InterviewBit/Anti Diagonals.cpp

I have added the solution of the problem named as "Anti Diagonals" of InterviewBit using C++ programming language. Path of the question : Interviewbit -> Programming -> Arrays -> Simulation Array -> Anti Diagonals
Link for the question : https://www.interviewbit.com/problems/anti-diagonals/

Create Anti Diagonals.cpp

---

leetcode/Java/Permutations.java

Leetcode 46 : https://leetcode.com/problems/permutations/

Created Permutations.java from Leetcode

---

Hackerrank/c++/QHEAP1.cpp
readme.md

This is solution for HackerRank question QHEAP1, link of which is- https://www.hackerrank.com/challenges/qheap1/problem 
This is solution for HackerRank question QHEAP1, link of which is- https://www.hackerrank.com/challenges/qheap1/problem 

QHEAP1 HackerRank solution added

---

Codeforces_Contests/Educational Codeforces Round 96/A.cpp
Codeforces_Contests/Educational Codeforces Round 96/B.cpp
Codeforces_Contests/Educational Codeforces Round 96/C.cpp

- [#] Make sure your files are in the right folder!
- [#] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [#] If your code is a solution for a code problem, please tell which one.
- [#] Make sure your code is working, test for a lot of cases.
Added solutions to A, B and C problem of Codeforces Educational Codeforces Round 96.

Added Codeforces contest Solutions

---

classical_algorithms/c++/bucketsort.cpp

Added the bucket sort algorithm for C++.

Added bucketsort.cpp

---

classical_algorithms/dart/BubbleSort.dart
readme.md

A function to BubbleSort a Array of Int, in Dart Language.

Add BubbleSort in Dart Language

---

leetcode/python/strings/count_and_say.py

I added a new folder [strings] for strings problems on leetcode/python folders and added the solution for problem 38. Count and Say

Add strings folder and add solution 38. Count and Say - LeetCode

---

classical_algorithms/java/BinarySearch.java

Added Binary Search in Java
NOTE:Binary Search only work for sorted Array,

Binary Search Added to Java

---

Hacker Earth/Algorithms/Graphs/Shortest Path Algorithms/A closest product.py
Hacker Earth/README.md

Created Hacker Earth Folder and added solution for A Closest Product problem  

---

leetcode/cpp/Array/190.cpp

Added Leetcode Reverse Bits solution

---

classical_algorithms/c++/dijkstra_implement..cpp

dijkstra's shortest path algorithm implemented in C++ with comments to explain each and every step of the algorithm
Added Dijkstra_implementation.cpp in C++ folder under the classic algorithms 
Dijkstra's shortest path algorithm implementation in C++
checked for several strong test cases

Dijkstra_implementation.cpp

---

Codeforces_Contests/Round_638_Div_2/A.cpp
Codeforces_Contests/Round_638_Div_2/B.cpp
readme.md

Added Codeforces Round 638 Problem A & Problem B

Added Codeforces Round 638 Problem A & Problem B

---

leetcode/python/Trie/Implement_Trie.py

Created a folder for Trie for Leetcode and added problem no: 208 - Implement Trie in python language.

Adding Leetcode Problem 208. Implement Trie

---

leetcode/cpp/Tree/559.cpp

Solution of leetcode problem "Maximum Depth of N-ary Tree" is added in Tree folder under cpp. Added code is simple and optimized solution.

Added 559.Maximum Depth of N-ary Tree using DFS

---

leetcode/cpp/Array/35.cpp

leedcode problem #35 Search Insert Position

---

leetcode/java/sets/PerfectRectangle391.java

Problem: https://leetcode.com/problems/perfect-rectangle/
O(n*log(n)) solution using TreeSet.

Leetcode Problem 391 Perfect Rectangle

---

leetcode/python/arrays/best_time_to_buy_sell_stock.py
leetcode/python/arrays/container_with_most_water.py
leetcode/python/arrays/first_last_position_sorted_array.py
leetcode/python/arrays/product_array_except_self.py
leetcode/python/arrays/search_in_rotated_sorted_array.py

Added python solutions to questions:
- Best time to buy and sell stock
- Search in rotated sorted array
- First and last position in sorted array
- Container with most water
- Product array except self

Added solutions to leetcode problems under arrays

---

CodeChef_problems/CVDRUN.cpp

Covid Run ( October Challenge 2020 Division 2)
CodeChef platform 
linke :https://www.codechef.com/OCT20B/problems/CVDRUN/

Added code of Covid Run Problem

---

classical_algorithms/c++/DSU_implementation.cpp

AmanMishra.md

---

leetcode/cpp/Array/523.cpp

Added solution for leetcode problem 523 in Array folder.
Title - Continuous Subarray Sum
Solved using hashmap in C++.

leetcodeproblem_523

---

classical_algorithms/java/AVL_Tree.java
classical_algorithms/java/BreadthFirstTraversal.java
classical_algorithms/java/DepthFirstTraversal.java
classical_algorithms/java/Egg_Drop.java
classical_algorithms/java/Kadane_Algorithm.java
classical_algorithms/java/LongestCommonSubsequence.java

Added the codes for many Java algorithms !

Added Avl tree, BFS, DFS, Egg Drop problem, Kadane Algo, LCS for JAVA

---

Hackerrank/30 days of code/Day25_RunningTimeAndComplexity.java
Hackerrank/java/Java_2D_Array.java
Hackerrank/java/Java_String_Tokens.java

Solutions added for Java and 30 Days of Code problems on HackerRank platform

Hackerrank- Java and 30DaysOfCode solutions added

---

leetcode/Java/ContainerWithMostWater.java

Solution to the Problem - Leetcode #11 - Container with Most Water in Java
Link to the problem : https://leetcode.com/problems/container-with-most-water/

Added ContainerWithMostWater.java| Leetcode - 11

---

classical_algorithms/dart/QuickSort.dart
readme.md

Added QuickSort code in Dart Language.

Add QuickSort in Dart

---

classical_algorithms/dart/BinarySort.dart
classical_algorithms/dart/QuickSort.dart
readme.md

Added Binary Sort code in Dart Language.

Add Binary Sort in Dart

---

classical_algorithms/c++/bogosort.cpp
readme.md

Added bogo sort and its entry on readme.md. Also added the missing entry for bucket sort.

Added bogosort.cpp

---

Hacker Earth/Algorithms/Graphs/Articulation points and bridges/edges on a path.py

Added solution for a edges on graph problem in hacker earth

---

leetcode/python/Dynamic Programming/120.triangle.py

Added LeetCode 120 Triangle python solution

---

leetcode/python/Dynamic Programming/198.House Robber.py

Added Leetcode 198 House Robber Solution

---

leetcode/python/Dynamic Programming/312.Burst_Balloons.py

Added Leetcode 312 Burst Balloons solution

---

leetcode/cpp/Stacks/682.cpp
leetcode/cpp/linkedlist/1290.cpp

Added solution to Leetcode problem 1290

---

leetcode/python/Dynamic Programming/413.Arithmetic_Series.py

Added Leetcode 413 Arithmetic Series Solution

---

classical_algorithms/c++/Bellman_Ford_Algo_Q.cpp

Bellman Ford algorithm implemented in C++
Bellman Ford implementation in C++ added in the C++ folder under classical_algorithms
Code has been tested on several strong test cases

Bellman_Ford_implementation.cpp

---

leetcode/cpp/dynamic programming/983.cpp

I added a solution to the problem no. 983 on LeetCode (Minimum Cost for Tickets).
It can be found in leetcode/cpp/dynamic programming/983.cpp

Leetcode problem 983

---

data_structures/Java/stack/stack.java

added stack DS

---

leetcode/cpp/linkedlist/206.cpp

Added solution to Leetcode Problem #206

---

leetcode/java/CircularArrayLoop.java
leetcode/java/stack/NextGreaterNodeInLinkedList.java

Problem links: 
1. https://leetcode.com/problems/next-greater-node-in-linked-list/
(Problem provides data as linked list, but main logic is to use a stack, so I have added this in stack folder.)
2. https://leetcode.com/problems/circular-array-loop/

LeetCode Problems 1019, 457

---

CodeChef_problems/Div2_October_cookoff_2020/Decreasing_Srrnmieeda.cpp
CodeChef_problems/Div2_October_cookoff_2020/Path_etic_Sums.cpp
CodeChef_problems/Div2_October_cookoff_2020/Split_the_Str_Ing.cpp
CodeChef_problems/Div2_October_cookoff_2020/Yet_Another_Crossover_Episode.cpp
Codeforces_Contests/grankforce/A_Circle_Coloring.cpp
Codeforces_Contests/grankforce/B_Arrays_Sum.cpp
Codeforces_Contests/grankforce/C_Discrete_Acceleration.cpp
Codeforces_Contests/grankforce/D_Searchlights.cpp
Codeforces_Contests/grankforce/problem_links.md

Added solutions for problem 1-4 of codechef cook off october 2020 

Cook Off October 2020

---

Codeforces_Contests/9_Round_677_Div_3/A.cpp
Codeforces_Contests/9_Round_677_Div_3/B.cpp
Codeforces_Contests/9_Round_677_Div_3/C.cpp
Codeforces_Contests/9_Round_677_Div_3/D.cpp
Codeforces_Contests/9_Round_677_Div_3/E.cpp
readme.md

The solutions of the first five problems (A, B, C, D, E) of Codeforces Round #677 Div 3 conducted on October 20, 2020

Added A, B, C, D, E solutions of Codeforces Round #677 Div 3 in C++

---

data_structures/C/Linked_List.c
data_structures/C/Stack.c

I didn't found codes of C language so made new folder in data structures for C language and added linked_list and stack data structure. 

linked_list and stack in C

---

leetcode/cpp/linkedlist/2.cpp

Added solution to Leetcode Problem #2

---

leetcode/cpp/backtracking/46(Permuations).cpp

- [done ] Make sure your files are in the right folder!
- [ done] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [ done] If your code is a solution for a code problem, please tell which one.
- [ done] Make sure your code is working, test for a lot of cases.
solved and added backtracking solution of Permutations question Leetcode in c++.

added 46(Permutations) in leetcode/backtracking/cpp

---

Codewars/Javascript/Bouncing_Balls.js
Codewars/Javascript/Build_A_Square.js
Codewars/Javascript/Multiply.js
Codewars/Javascript/Number_Of_People_In_The_Buss.js
Codewars/Javascript/Simple_Pig_Latin.js

Added Codewars solution

---

SPOJ/C/BSCXOR.c
SPOJ/C/CHITEST1.c
SPOJ/C/SMPSUM.c
SPOJ/CPP/AGGRCOW.cpp
SPOJ/Python/TMUL.py

Added SPOJ solutions

---

CodeChef_problems/Average Number.cpp

This is the solution of the CodeChef problem Average Number
https://www.codechef.com/problems/AVG

Create Average Number.cpp

---

leetcode/python/Dynamic Programming/746.min_cost_climbing_stairs.py

add code for problem 746 leetcode

---

cracking_the_code/Q1.1_is_unique.py

resolution Q1.1

---

leetcode/csharp/ShuffleArray.cs

I added a C# folder under the Leetcode folder. I then added a solution for problem #670. The URL of the problem is at the top of the .cs file.

Added C# folder under Leetcode and solution for problem #670

---

cracking_the_code/chapter2/Q2.2-kth-to-last.py
cracking_the_code/chapter2/linked_list.py

add Q2.2 return kth to last

---

cracking_the_code/chapter3/stack.py

stack library

---

cracking_the_code/chapter3/queue.py

add queue class

---

cracking_the_code/chapter3/Q3.1-three-in-one.py

add class MultiStack

---

cracking_the_code/chapter3/Q3.2-stack-min.py
cracking_the_code/chapter3/stack.py

chapter 3 question 2 - Cracking the Code Interview

---

cracking_the_code/chapter3/Q3.4-myqueue.py

add Q3.4 CCI

---

cracking_the_code/chapter3/Q3.5-sort-stack.py

Q5 chapter 3 sort stack

---

leetcode/python/arrays/26_remove_duplicates_from_sorted_array.py

first version question 26 array

---

leetcode/python/strings/344_reverse_string.py

reverse string

---

leetcode/python/linked_lists/delete_node_linked_list.py

q1 leetcode linked-list

---

cracking_the_code/chapter4/graph.py
cracking_the_code/chapter4/route_between_nodes.py

add graph 

---

cracking_the_code/chapter4/minimal_tree_v2.py

add draft code minimal_tree

---

leetcode/python/sorting_and_searching/merge_sorted_array.py

merged sorted array v1

---

leetcode/python/Dynamic Programming/climbing_stairs.py

add problem climbing stairs

---

leetcode/python/design/shuffle_array.py

add problem shuffle array

---

CodeChef_problems/Camp Or Not.cpp

This is the solution for the CodeChef problem Camp Or Not.
https://www.codechef.com/problems/CAMPON

Create Camp Or Not.cpp

---

leetcode/python/design/min_stack.py

min_stack code v1

---

leetcode/python/others/number-of-1-bits.py

leetcode number of 1 bits

---

leetcode/python/others/hamming_distance.py

hamming distance problem

---

Codility/cyclic_rotation.py

cyclic rotation question codility

---

Codility/cyclic_rotation.py

add solution 2

---

Codility/odd_occurrences_in_array.py

add solution to oddReccurrencesInArray - codility

---

Codility/perm_missing_element.py

add permMissingElement code

---

Codility/tape_equilibrium.py

solution tape_equilibrium

---

Codility/frog_river_one.py

https://app.codility.com/programmers/lessons/4-counting_elements/frog_river_one/

question frog river one

---

Codility/maxCounters.py

maxCounters 

---

Codility/perm_check.py

https://app.codility.com/programmers/lessons/4-counting_elements/perm_check/

code for perm_check problem

---

leetcode/cpp/Array/42.cpp

Added 42.cpp 
Added the file in the correct folder: Array in cpp in leetcode
**Question :** Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.
**Solution :** The solution is in C++ language.
I am a participant of **Hacktoberfest 2021**. Kindly review and merge this branch or please label it as 'hacktoberfest-accepted' . Thank You !!
**Related issue :** #27

Added 42.cpp 

---

leetcode/cpp/linkedlist/147.cpp
leetcode/cpp/linkedlist/148.cpp

This is the solution for leetcode problem 147: Sort List and 148: Insertion Sort List
I'm a HacktoberFest 2021 participant, please merge my PR and tag it as 'hacktoberfest-accepted'

added cpp solutions for leetcode problems

---

leetcode/cpp/string/1328.cpp

Added solution for Problem number 1328. Break A Palindrome (Leetcode) in C++ language

Added solution for 1328.Break A Palindrome (Leetcode) in C++ language

---

Codility/missing_integer.py

https://app.codility.com/programmers/lessons/4-counting_elements/missing_integer/

Codility - Missing Integer

---

data_structures/C/binarytree.c
data_structures/C/treeheight.c
data_structures/C/treetraversal.c

uploaded trees data structures problems solutions.

---

Codility/passing_cars.py

Passing Cars - Codility

---

Hackerrank/python/Fraudulent Activity Notification/fraud_notification.py

Solution for Fraudulent Activity Notification.

fraudulent activity notification solution

---

Hackerrank/python/Fraudulent Activity Notification/Readme.md

Hackerrank problem of Fraudulent Activity Notification.

hackerrank problem statement

---

leetcode/python/linked_lists/Flatten_a_Multilevel_Doubly_Linked_List.py
readme.md

- [Done ] Make sure your files are in the right folder!
- [Done ] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [[Done](https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/) ] If your code is a solution for a code problem, please tell which one.
- [ Done] Make sure your code is working, test for a lot of cases.
Created Leetcode: Flatten a Multilevel Doubly Linked List.py

Create Leetcode: Flatten a Multilevel Doubly Linked List.py

---

leetcode/sql/second-hihest-salary.sql

leetcode second-highest-salary

---

Codility/python/min_avg_two_slices.py

https://app.codility.com/programmers/lessons/5-prefix_sums/min_avg_two_slice/

min avg two slices

---

leetcode/sql/rank-scores.sql

https://leetcode.com/problems/rank-scores/

leetcode rank-scores sql

---

leetcode/sql/consecutive_numbers.sql

https://leetcode.com/problems/consecutive-numbers/submissions/

leetcode consecutive-numbers problem

---

leetcode/sql/employees-earning-more-than-their-managers.sql

[Problem](https://leetcode.com/problems/employees-earning-more-than-their-managers/submissions/)

leetcode employees-earning-more-than-their-managers

---

leetcode/sql/department-highest-salary.sql

[Problem](https://leetcode.com/problems/employees-earning-more-than-their-managers/submissions/)

department-highest-salary

---

Codility/python/max_product_of_three.py

Max Product of Three

---

Codility/python/triangle.py

add codility problem: triangle

---

Codility/python/brackets.py

brackets question codility

---

Codility/python/fish.py

add codility question fish

---

InterviewBit/Dynamic_Programming/Readme.md
InterviewBit/Dynamic_Programming/merge_elements.cpp
readme.md

Solution of InterviewBit's DP's merge_element was added.

---

Codility/python/nesting.py

add problem nesting codility

---

.github/workflows/task-list-checker.yml

add task list checker

---

data_structures/C++/Graph/graphColoring.cpp

solved graph coloring problem!!

graph coloring

---

Project Euler/cpp/86.cpp

Added solution for Project Euler #86 in C++

Added solution for Project Euler #86 in C++

---

leetcode/python/arrays/rotate_array.py

first version rotate-array

---

readme.md

Hey, I have added a reference link for Data Structures Tutorial. I came upon this article while looking for resources to learn Data Structures. This citation, in my opinion, will enhance the content of this article. Hope that my contribution will benefit other learners.

Added a new resource

---

Hackerrank/python/utopian_tree.py

Adding answer to Hackerrank Utopian Tree problem with Python, it passed the test case in platform
If you don't mind to put hacktoberfest-accepted tag to this PR to meet criteria. Cheers :+1:  #hacktoberfest

Add Utopian Tree answer with Python

---

readme.md

Added quick access links in the readme.md file to access newly added problems' solutions
@larissalages

Added Quick link to newly added problems' solutions

---

leetcode/cpp/Tree/1026.cpp

added leetcode solution for 1026

---

classical_algorithms/c++/Binary_Search.cpp
classical_algorithms/c++/Linear_Search.cpp
readme.md

I have added Linear Search and Binary Search algorithms in C++ folder of classical_algorithms .

Added Search algorithms in C++ folder of classical_algorithms

---

leetcode/sql/actors-and-directors-who-cooperated-at-least-three-times.sql
leetcode/sql/article-views-1.sql

Added LeetCode #1050, #1148 solutions in MySQL

---

leetcode/sql/sales-analysis-iii.sql

Added LeetCode #1084 solution in MySQL

---

leetcode/sql/top-travellers.sql

Add LeetCode #1407 solution in MySQL

---

leetcode/sql/patients-with-a-condition.sql

Add LeetCode #1527 solution in MySQL

---

leetcode/sql/sales-person.sql

Add LeetCode #607 solution in MySQL

---

leetcode/sql/combine-two-tables.sql

Add LeetCode #175 solution in MySQL

---

classical_algorithms/C/Binary_Search.c
classical_algorithms/C/Linear_Search.c
readme.md

I have added Linear Search and Binary Search in C folder in classical_algorithms folder .

Added linear search and binary search in C language .

---

leetcode/Javascript/BinarySearch/koko_eating_bananas.js

My solution for the Leetcode problem [Koko Eating Bananas](https://leetcode.com/problems/koko-eating-bananas/) in JavaScript.
Resolves https://github.com/larissalages/code_problems/issues/421

Add Solution for Koko Eating Bananas

---

leetcode/cpp/linkedlist/2095.cpp

Solution of LC-2095 added in cpp

---

CodeChef_problems/Codechef-October-Long-Challenge-2022/Building_Race.cpp
CodeChef_problems/Codechef-October-Long-Challenge-2022/SingleOp1.cpp
CodeChef_problems/Codechef-October-Long-Challenge-2022/SingleOp2.cpp

Please tag me accepted for hacktober fest 2022.

Codechef Long challenge October 2022

---

leetcode/cpp/Greedy/Minimum Time to Make Rope Colorful.cpp

Leetcode Problem : 1578. Minimum Time to Make Rope Colorful
Problem Link : https://leetcode.com/problems/minimum-time-to-make-rope-colorful/

Minimum Time to Make Rope Colorful.cpp

---

leetcode/cpp/Array/1920. Build Array from Permutation.cpp

Added https://leetcode.com/problems/build-array-from-permutation/description/ .

1920. Build Array from Permutation.cpp

---

leetcode/sql/FindCustomerRefree.sql

Changes made by akruti sarangi added new sql leetcode problem to project

---

leetcode/cpp/Binary Search/Median of Two Sorted Arrays.cpp

Problem Number: 4
Problem Name: Median of Two Sorted Arrays
Problem Link: https://leetcode.com/problems/median-of-two-sorted-arrays/

Median of Two Sorted Arrays.cpp

---

Codeforces_Contests/Round_739_Div_3/A.cpp
Codeforces_Contests/Round_739_Div_3/B.cpp
Codeforces_Contests/Round_739_Div_3/C.cpp

I have added solution of problems A B C of codeforces div 3 round 739

added solution of div 3 round 739 A B C

---

classical_algorithms/c++/dfs.cpp
readme.md

I have added depth first search algorithm in C++ in classical_algorithms folder .

Added Depth First Search Algorithm in C++

---

classical_algorithms/C/dfs.c
readme.md

I have added Depth First Search algorithm in C folder of classical_algorithms folder .

Added dfs algorithm in C

---

data_structures/C++/Binary Trees/Traversal/inorder.cpp

solved with optimized complexity

inorder traversal of tree

---

leetcode/cpp/linkedlist/160.cpp

Solution of LC-160 has been added in CPP.

Solution of LC-160 added in CPP

---

Hackerrank/SQL/Latitude & Longitude~ MySQL.sql

hi @larissalages made the requested changes! thanks:)

MySQL question added

---

leetcode/cpp/Tree/99.cpp

Added leetcode problem 99. Recover Binary Search Tree

added cpp leetcode solutions

---

Codeforces_Contests/Round_828_Div_3/A_Number_Replacement.cpp
Codeforces_Contests/Round_828_Div_3/B_Even-Odd_Increments.cpp
Codeforces_Contests/Round_828_Div_3/C_Traffic_Light.cpp
Codeforces_Contests/Round_828_Div_3/D_Divisibility_by_2_n.cpp
Codeforces_Contests/Round_828_Div_3/E_1_Divisible_Numbers_easy_version.cpp
Codeforces_Contests/Round_828_Div_3/E_2_Divisible_Numbers_hard_version.cpp

I solved six problems in the contest codeforces_round_828_Div_3.

Intial Commit

---

Hackerrank/SQL/Latitude & Longitude~ MySQL.sql
data_structures/Javascript/stack.js

> How to make a JS array to behave like a Stack

Make a Stack structure with JS

---

matrix_2d_mult.py

mult matrices
